// <auto-generated />
using System;
using DeWaveFreeAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DeWaveFreeAPI.Migrations
{
    [DbContext(typeof(DeWaveAPIDbContext))]
    [Migration("20260507181410_AddIdentityToCourseDetail")]
    partial class AddIdentityToCourseDetail
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DeWaveFreeAPI.Models.BlockType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("PK__block_ty__3213E83FDC459AAD");

                    b.HasIndex(new[] { "Name" }, "UQ__block_ty__72E12F1B3F33E3D0")
                        .IsUnique();

                    b.ToTable("block_types");
                });

            modelBuilder.Entity("DeWaveFreeAPI.Models.Blog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AuthorId")
                        .HasColumnType("int")
                        .HasColumnName("author_id");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int")
                        .HasColumnName("category_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("published_at");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("slug");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("draft")
                        .HasColumnName("status");

                    b.Property<string>("Summary")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("summary");

                    b.Property<string>("ThumbnailUrl")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("thumbnail_url");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<int>("ViewCount")
                        .HasColumnType("int")
                        .HasColumnName("view_count");

                    b.HasKey("Id")
                        .HasName("PK__blog__3213E83FF4ACE46E");

                    b.HasIndex(new[] { "Slug" }, "UQ__blog__32DD1E4C9A687D8B")
                        .IsUnique();

                    b.ToTable("blog");
                });

            modelBuilder.Entity("DeWaveFreeAPI.Models.BlogDetail", b =>
                {
                    b.Property<int>("BlogId")
                        .HasColumnType("int")
                        .HasColumnName("blog_id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("content");

                    b.Property<string>("ExtraJson")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("extra_json");

                    b.Property<string>("SeoDescription")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("seo_description");

                    b.Property<string>("SeoKeywords")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("seo_keywords");

                    b.Property<string>("SeoTitle")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("seo_title");

                    b.Property<string>("Tags")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("tags");

                    b.HasKey("BlogId")
                        .HasName("PK__blog_det__2975AA2855C60D32");

                    b.ToTable("blog_details");
                });

            modelBuilder.Entity("DeWaveFreeAPI.Models.BlogTag", b =>
                {
                    b.Property<int>("BlogId")
                        .HasColumnType("int")
                        .HasColumnName("blog_id");

                    b.Property<string>("Tag")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("tag");

                    b.HasKey("BlogId", "Tag")
                        .HasName("PK__blog_tag__34B4ABE8F7FE4C7E");

                    b.ToTable("blog_tags");
                });

            modelBuilder.Entity("DeWaveFreeAPI.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id")
                        .HasName("PK__Category__3214EC0713EA737F");

                    b.ToTable("category");
                });

            modelBuilder.Entity("DeWaveFreeAPI.Models.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int?>("Duration")
                        .HasColumnType("int")
                        .HasColumnName("duration");

                    b.Property<string>("Image")
                        .HasColumnType("text")
                        .HasColumnName("image");

                    b.Property<string>("Instructor")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("instructor");

                    b.Property<int>("InstructorId")
                        .HasColumnType("int")
                        .HasColumnName("instructor_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("IsActive");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("price");

                    b.Property<decimal?>("Rating")
                        .HasColumnType("decimal(3, 2)")
                        .HasColumnName("rating");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("title");

                    b.Property<int?>("VideoCount")
                        .HasColumnType("int")
                        .HasColumnName("video_count");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("courses");
                });

            modelBuilder.Entity("DeWaveFreeAPI.Models.CourseApplication", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Course")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CvfileName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("CVFileName");

                    b.Property<string>("CvfilePath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("CVFilePath");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Pending");

                    b.Property<DateTime?>("SubmittedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getutcdate())");

                    b.HasKey("Id")
                        .HasName("PK__CourseAp__3214EC0783C8197B");

                    b.ToTable("CourseApplications");
                });

            modelBuilder.Entity("DeWaveFreeAPI.Models.CourseDetail", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int?>("CourseId")
                        .HasColumnType("int")
                        .HasColumnName("course_id");

                    b.Property<string>("FullDescriptionHtml")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HeroImage")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("hero_image");

                    b.Property<string>("ShortDescription")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ToolsRequired")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id")
                        .HasName("PK__course_d__3213E83F07F62793");

                    b.HasIndex("CourseId");

                    b.ToTable("course_details");
                });

            modelBuilder.Entity("DeWaveFreeAPI.Models.CourseEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Capacity")
                        .HasColumnType("int")
                        .HasColumnName("capacity");

                    b.Property<string>("Color")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("color");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("int")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("end_time");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("online")
                        .HasColumnName("event_type");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Location")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("location");

                    b.Property<string>("MeetingUrl")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("meeting_url");

                    b.Property<string>("PreviewVideoUrl")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("preview_video_url");

                    b.Property<bool>("RequiresRegistration")
                        .HasColumnType("bit")
                        .HasColumnName("requires_registration");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("start_time");

                    b.Property<string>("ThumbnailUrl")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("thumbnail_url");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("title");

                    b.Property<bool>("TrackAttendance")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("track_attendance");

                    b.Property<string>("Visibility")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("course_only")
                        .HasColumnName("visibility");

                    b.HasKey("Id")
                        .HasName("PK__course_e__3213E83F82862F97");

                    b.HasIndex(new[] { "StartTime" }, "idx_course_events_active")
                        .HasFilter("([is_active]=(1))");

                    b.HasIndex(new[] { "CreatedByUserId", "StartTime" }, "idx_course_events_created_by");

                    b.HasIndex(new[] { "Visibility", "StartTime" }, "idx_course_events_visibility_time");

                    b.ToTable("course_events");
                });

            modelBuilder.Entity("DeWaveFreeAPI.Models.CourseEventCourse", b =>
                {
                    b.Property<int>("EventId")
                        .HasColumnType("int")
                        .HasColumnName("event_id");

                    b.Property<int>("CourseId")
                        .HasColumnType("int")
                        .HasColumnName("course_id");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getutcdate())");

                    b.HasKey("EventId", "CourseId")
                        .HasName("PK__course_e__DB81185DFE7574B4");

                    b.HasIndex(new[] { "CourseId", "EventId" }, "idx_cec_course");

                    b.HasIndex(new[] { "EventId" }, "idx_cec_event");

                    b.ToTable("course_event_courses");
                });

            modelBuilder.Entity("DeWaveFreeAPI.Models.CourseFaq", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Answer")
                        .HasColumnType("text")
                        .HasColumnName("answer");

                    b.Property<int>("CourseId")
                        .HasColumnType("int")
                        .HasColumnName("course_id");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("question");

                    b.Property<int?>("SortOrder")
                        .HasColumnType("int")
                        .HasColumnName("sort_order");

                    b.HasKey("Id")
                        .HasName("PK__CourseFa__3214EC07576B2278");

                    b.HasIndex("CourseId");

                    b.ToTable("course_faqs");
                });

            modelBuilder.Entity("DeWaveFreeAPI.Models.CourseImage", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(24)
                        .IsUnicode(false)
                        .HasColumnType("varchar(24)")
                        .HasColumnName("id");

                    b.Property<string>("Caption")
                        .HasColumnType("text")
                        .HasColumnName("caption");

                    b.Property<int?>("DetailId")
                        .HasColumnType("int")
                        .HasColumnName("detail_id");

                    b.Property<bool?>("IsMainImage")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("is_main_image");

                    b.Property<int?>("Order")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("order");

                    b.Property<DateTime?>("UploadedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("uploaded_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("url");

                    b.HasKey("Id")
                        .HasName("PK__course_i__3213E83F9F132558");

                    b.HasIndex("DetailId");

                    b.ToTable("course_images");
                });

            modelBuilder.Entity("DeWaveFreeAPI.Models.CourseInstructor", b =>
                {
                    b.Property<int>("CourseId")
                        .HasColumnType("int")
                        .HasColumnName("course_id");

                    b.Property<int>("InstructorId")
                        .HasColumnType("int")
                        .HasColumnName("instructor_id");

                    b.Property<int>("InstructorTypeId")
                        .HasColumnType("int")
                        .HasColumnName("instructor_type_id");

                    b.Property<int?>("SortOrder")
                        .HasColumnType("int")
                        .HasColumnName("sort_order");

                    b.HasKey("CourseId", "InstructorId")
                        .HasName("PK_course_instructors");

                    b.HasIndex("InstructorId");

                    b.HasIndex("InstructorTypeId");

                    b.ToTable("course_instructors");
                });

            modelBuilder.Entity("DeWaveFreeAPI.Models.CourseLearningSection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CourseId")
                        .HasColumnType("int")
                        .HasColumnName("course_id");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int")
                        .HasColumnName("sort_order");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("PK__course_l__3213E83F738C8CE9");

                    b.HasIndex(new[] { "CourseId", "SortOrder" }, "idx_learning_sections_course");

                    b.ToTable("course_learning_sections");
                });

            modelBuilder.Entity("DeWaveFreeAPI.Models.CourseSection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ContentHtml")
                        .HasColumnType("text")
                        .HasColumnName("content_html");

                    b.Property<int>("CourseId")
                        .HasColumnType("int")
                        .HasColumnName("course_id");

                    b.Property<int?>("DurationMinutes")
                        .HasColumnType("int")
                        .HasColumnName("duration_minutes");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int")
                        .HasColumnName("sort_order");

                    b.Property<string>("ThumbnailUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("thumbnail_url");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("title");

                    b.Property<string>("VideoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("video_url");

                    b.HasKey("Id")
                        .HasName("PK__CourseSy__3214EC07BFACF63A");

                    b.HasIndex("CourseId");

                    b.ToTable("course_sections");
                });

            modelBuilder.Entity("DeWaveFreeAPI.Models.EventAttendance", b =>
                {
                    b.Property<int>("StudentId")
                        .HasColumnType("int")
                        .HasColumnName("student_id");

                    b.Property<int>("EventId")
                        .HasColumnType("int")
                        .HasColumnName("event_id");

                    b.Property<bool>("Attended")
                        .HasColumnType("bit")
                        .HasColumnName("attended");

                    b.Property<DateTime?>("JoinedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("joined_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("absent")
                        .HasColumnName("status");

                    b.HasKey("StudentId", "EventId")
                        .HasName("PK__event_at__480409E89F7B98DE");

                    b.HasIndex(new[] { "EventId", "StudentId" }, "idx_event_attendance_event");

                    b.ToTable("event_attendance");
                });

            modelBuilder.Entity("DeWaveFreeAPI.Models.EventEnrollment", b =>
                {
                    b.Property<int>("StudentId")
                        .HasColumnType("int")
                        .HasColumnName("student_id");

                    b.Property<int>("EventId")
                        .HasColumnType("int")
                        .HasColumnName("event_id");

                    b.Property<DateTime>("RegisteredAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("registered_at")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("registered")
                        .HasColumnName("status");

                    b.HasKey("StudentId", "EventId")
                        .HasName("PK__event_en__480409E874514955");

                    b.HasIndex(new[] { "EventId", "StudentId" }, "idx_event_enrollments_event");

                    b.ToTable("event_enrollments");
                });

            modelBuilder.Entity("DeWaveFreeAPI.Models.Instructor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Bio")
                        .HasColumnType("text")
                        .HasColumnName("bio");

                    b.Property<string>("Certifications")
                        .HasColumnType("text")
                        .HasColumnName("certifications");

                    b.Property<string>("ContactEmail")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("contact_email");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<string>("Headline")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("headline");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(512)
                        .IsUnicode(false)
                        .HasColumnType("varchar(512)")
                        .HasColumnName("image_url");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(14)
                        .IsUnicode(false)
                        .HasColumnType("char(14)")
                        .HasColumnName("phone_number")
                        .IsFixedLength();

                    b.Property<string>("Specialization")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("specialization");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("PK__instruct__3214EC070B3A630E");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasFilter("[user_id] IS NOT NULL");

                    b.ToTable("instructors");
                });

            modelBuilder.Entity("DeWaveFreeAPI.Models.InstructorType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("PK__instruct__3213E83F07A0CDBA");

                    b.HasIndex(new[] { "Name" }, "UQ__instruct__72E12F1B722BA49E")
                        .IsUnique();

                    b.ToTable("instructor_types");
                });

            modelBuilder.Entity("DeWaveFreeAPI.Models.Lesson", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<int>("SectionId")
                        .HasColumnType("int")
                        .HasColumnName("section_id");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int")
                        .HasColumnName("sort_order");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("PK__lessons__3213E83F94DDB14A");

                    b.HasIndex(new[] { "SectionId", "SortOrder" }, "idx_lessons_section");

                    b.ToTable("lessons");
                });

            modelBuilder.Entity("DeWaveFreeAPI.Models.LessonBlock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BlockTypeId")
                        .HasColumnType("int")
                        .HasColumnName("block_type_id");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("DataJson")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("data_json");

                    b.Property<int>("LessonId")
                        .HasColumnType("int")
                        .HasColumnName("lesson_id");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("int")
                        .HasColumnName("order_index");

                    b.HasKey("Id")
                        .HasName("PK__lesson_b__3213E83FFCC61603");

                    b.HasIndex("BlockTypeId");

                    b.HasIndex(new[] { "LessonId", "OrderIndex" }, "idx_blocks_lesson");

                    b.ToTable("lesson_blocks");
                });

            modelBuilder.Entity("DeWaveFreeAPI.Models.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(9, 2)")
                        .HasColumnName("amount");

                    b.Property<int>("CourseId")
                        .HasColumnType("int")
                        .HasColumnName("course_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<string>("OrderId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("order_id");

                    b.Property<string>("SnapToken")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("snap_token");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Pending")
                        .HasColumnName("status");

                    b.Property<int>("StudentId")
                        .HasColumnType("int")
                        .HasColumnName("student_id");

                    b.HasKey("Id")
                        .HasName("PK__Payments__3214EC075C33B68C");

                    b.HasIndex("CourseId");

                    b.HasIndex("StudentId");

                    b.ToTable("payments");
                });

            modelBuilder.Entity("DeWaveFreeAPI.Models.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("bit");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__RefreshT__3214EC07F8A50CB2");

                    b.HasIndex(new[] { "Token" }, "IX_RefreshTokens_Token")
                        .IsUnique();

                    b.HasIndex(new[] { "UserId" }, "IX_RefreshTokens_UserId");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("DeWaveFreeAPI.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id")
                        .HasName("PK__Roles__3214EC075882ED90");

                    b.HasIndex(new[] { "Name" }, "UQ__Roles__737584F621FF8B55")
                        .IsUnique();

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("DeWaveFreeAPI.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("address");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2")
                        .HasColumnName("date_of_birth");

                    b.Property<string>("EmergencyContact")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("emergency_contact");

                    b.Property<string>("EmergencyPhone")
                        .HasMaxLength(14)
                        .HasColumnType("nvarchar(14)")
                        .HasColumnName("emergency_phone");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("full_name");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(14)
                        .HasColumnType("nvarchar(14)")
                        .HasColumnName("phone_number");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Students__3214EC07B92067FA");

                    b.HasIndex(new[] { "UserId" }, "UX_Students_UserId")
                        .IsUnique();

                    b.ToTable("Students");
                });

            modelBuilder.Entity("DeWaveFreeAPI.Models.StudentCourse", b =>
                {
                    b.Property<int>("StudentId")
                        .HasColumnType("int")
                        .HasColumnName("student_id");

                    b.Property<int>("CourseId")
                        .HasColumnType("int")
                        .HasColumnName("course_id");

                    b.Property<DateTime>("EnrolledAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("enrolled_at")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.HasKey("StudentId", "CourseId");

                    b.HasIndex("CourseId");

                    b.ToTable("student_courses");
                });

            modelBuilder.Entity("DeWaveFreeAPI.Models.StudentLessonProgress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CompletedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("completed_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("LessonId")
                        .HasColumnType("int")
                        .HasColumnName("lesson_id");

                    b.Property<int>("StudentId")
                        .HasColumnType("int")
                        .HasColumnName("student_id");

                    b.HasKey("Id")
                        .HasName("PK__student___3213E83F5ED50D46");

                    b.HasIndex(new[] { "StudentId", "LessonId" }, "UQ_student_lesson")
                        .IsUnique();

                    b.HasIndex(new[] { "LessonId" }, "idx_slp_lesson_id");

                    b.HasIndex(new[] { "StudentId" }, "idx_slp_student_id");

                    b.ToTable("student_lesson_progress");
                });

            modelBuilder.Entity("DeWaveFreeAPI.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("DisplayId")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("EmailVerificationToken")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsEmailVerified")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PasswordResetToken")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("PasswordResetTokenExpires")
                        .HasColumnType("datetime");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id")
                        .HasName("PK__Users__3214EC072DC8FA20");

                    b.HasIndex("RoleId");

                    b.HasIndex(new[] { "Email" }, "IX_Users_Email");

                    b.HasIndex(new[] { "DisplayId" }, "UQ_Users_DisplayId")
                        .IsUnique();

                    b.HasIndex(new[] { "Email" }, "UQ_Users_Email")
                        .IsUnique()
                        .HasFilter("[Email] IS NOT NULL");

                    b.HasIndex(new[] { "Username" }, "UQ__Users__536C85E4FCAACD33")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("DeWaveFreeAPI.Models.UserSequence", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("LastSequence")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<byte>("Month")
                        .HasColumnType("tinyint");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("RolePrefix")
                        .IsRequired()
                        .HasMaxLength(2)
                        .IsUnicode(false)
                        .HasColumnType("char(2)")
                        .IsFixedLength();

                    b.Property<short>("Year")
                        .HasColumnType("smallint");

                    b.HasKey("Id")
                        .HasName("PK__UserSequ__3214EC07E4B097EC");

                    b.HasIndex(new[] { "Role", "Month", "Year" }, "UQ_UserSequences")
                        .IsUnique();

                    b.ToTable("user_sequences");
                });

            modelBuilder.Entity("DeWaveFreeAPI.Models.BlogDetail", b =>
                {
                    b.HasOne("DeWaveFreeAPI.Models.Blog", "Blog")
                        .WithOne("BlogDetail")
                        .HasForeignKey("DeWaveFreeAPI.Models.BlogDetail", "BlogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_blog_details_blog");

                    b.Navigation("Blog");
                });

            modelBuilder.Entity("DeWaveFreeAPI.Models.BlogTag", b =>
                {
                    b.HasOne("DeWaveFreeAPI.Models.Blog", "Blog")
                        .WithMany("BlogTags")
                        .HasForeignKey("BlogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_blog_tags_blog");

                    b.Navigation("Blog");
                });

            modelBuilder.Entity("DeWaveFreeAPI.Models.Course", b =>
                {
                    b.HasOne("DeWaveFreeAPI.Models.Category", "Category")
                        .WithMany("Courses")
                        .HasForeignKey("CategoryId")
                        .HasConstraintName("FK_Course_Category");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("DeWaveFreeAPI.Models.CourseDetail", b =>
                {
                    b.HasOne("DeWaveFreeAPI.Models.Course", "Course")
                        .WithMany("CourseDetails")
                        .HasForeignKey("CourseId")
                        .HasConstraintName("FK_course_details_courses");

                    b.Navigation("Course");
                });

            modelBuilder.Entity("DeWaveFreeAPI.Models.CourseEvent", b =>
                {
                    b.HasOne("DeWaveFreeAPI.Models.User", "CreatedByUser")
                        .WithMany("CourseEvents")
                        .HasForeignKey("CreatedByUserId")
                        .IsRequired()
                        .HasConstraintName("fk_course_events_user");

                    b.Navigation("CreatedByUser");
                });

            modelBuilder.Entity("DeWaveFreeAPI.Models.CourseEventCourse", b =>
                {
                    b.HasOne("DeWaveFreeAPI.Models.Course", "Course")
                        .WithMany("CourseEventCourses")
                        .HasForeignKey("CourseId")
                        .IsRequired()
                        .HasConstraintName("fk_cec_course");

                    b.HasOne("DeWaveFreeAPI.Models.CourseEvent", "Event")
                        .WithMany("CourseEventCourses")
                        .HasForeignKey("EventId")
                        .IsRequired()
                        .HasConstraintName("fk_cec_event");

                    b.Navigation("Course");

                    b.Navigation("Event");
                });

            modelBuilder.Entity("DeWaveFreeAPI.Models.CourseFaq", b =>
                {
                    b.HasOne("DeWaveFreeAPI.Models.Course", "Course")
                        .WithMany("CourseFaqs")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_CourseFaq_Course");

                    b.Navigation("Course");
                });

            modelBuilder.Entity("DeWaveFreeAPI.Models.CourseImage", b =>
                {
                    b.HasOne("DeWaveFreeAPI.Models.CourseDetail", "Detail")
                        .WithMany("CourseImages")
                        .HasForeignKey("DetailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK__course_im__detai__6754599E");

                    b.Navigation("Detail");
                });

            modelBuilder.Entity("DeWaveFreeAPI.Models.CourseInstructor", b =>
                {
                    b.HasOne("DeWaveFreeAPI.Models.Course", "Course")
                        .WithMany("CourseInstructors")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_course_instructors_courses");

                    b.HasOne("DeWaveFreeAPI.Models.Instructor", "Instructor")
                        .WithMany("CourseInstructors")
                        .HasForeignKey("InstructorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_course_instructors_instructors");

                    b.HasOne("DeWaveFreeAPI.Models.InstructorType", "InstructorType")
                        .WithMany("CourseInstructors")
                        .HasForeignKey("InstructorTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Instructor");

                    b.Navigation("InstructorType");
                });

            modelBuilder.Entity("DeWaveFreeAPI.Models.CourseLearningSection", b =>
                {
                    b.HasOne("DeWaveFreeAPI.Models.Course", "Course")
                        .WithMany("CourseLearningSections")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_learning_sections_course");

                    b.Navigation("Course");
                });

            modelBuilder.Entity("DeWaveFreeAPI.Models.CourseSection", b =>
                {
                    b.HasOne("DeWaveFreeAPI.Models.Course", "Course")
                        .WithMany("CourseSections")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_CourseSyllabus_Course");

                    b.Navigation("Course");
                });

            modelBuilder.Entity("DeWaveFreeAPI.Models.EventAttendance", b =>
                {
                    b.HasOne("DeWaveFreeAPI.Models.CourseEvent", "Event")
                        .WithMany("EventAttendances")
                        .HasForeignKey("EventId")
                        .IsRequired()
                        .HasConstraintName("fk_event_attendance_event");

                    b.HasOne("DeWaveFreeAPI.Models.Student", "Student")
                        .WithMany("EventAttendances")
                        .HasForeignKey("StudentId")
                        .IsRequired()
                        .HasConstraintName("fk_event_attendance_student");

                    b.Navigation("Event");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("DeWaveFreeAPI.Models.EventEnrollment", b =>
                {
                    b.HasOne("DeWaveFreeAPI.Models.CourseEvent", "Event")
                        .WithMany("EventEnrollments")
                        .HasForeignKey("EventId")
                        .IsRequired()
                        .HasConstraintName("fk_event_enrollments_event");

                    b.HasOne("DeWaveFreeAPI.Models.Student", "Student")
                        .WithMany("EventEnrollments")
                        .HasForeignKey("StudentId")
                        .IsRequired()
                        .HasConstraintName("fk_event_enrollments_student");

                    b.Navigation("Event");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("DeWaveFreeAPI.Models.Instructor", b =>
                {
                    b.HasOne("DeWaveFreeAPI.Models.User", "User")
                        .WithOne("Instructor")
                        .HasForeignKey("DeWaveFreeAPI.Models.Instructor", "UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DeWaveFreeAPI.Models.Lesson", b =>
                {
                    b.HasOne("DeWaveFreeAPI.Models.CourseLearningSection", "Section")
                        .WithMany("Lessons")
                        .HasForeignKey("SectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_lessons_section");

                    b.Navigation("Section");
                });

            modelBuilder.Entity("DeWaveFreeAPI.Models.LessonBlock", b =>
                {
                    b.HasOne("DeWaveFreeAPI.Models.BlockType", "BlockType")
                        .WithMany("LessonBlocks")
                        .HasForeignKey("BlockTypeId")
                        .IsRequired()
                        .HasConstraintName("FK_blocks_type");

                    b.HasOne("DeWaveFreeAPI.Models.Lesson", "Lesson")
                        .WithMany("LessonBlocks")
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_blocks_lesson");

                    b.Navigation("BlockType");

                    b.Navigation("Lesson");
                });

            modelBuilder.Entity("DeWaveFreeAPI.Models.Payment", b =>
                {
                    b.HasOne("DeWaveFreeAPI.Models.Course", "Course")
                        .WithMany("Payments")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DeWaveFreeAPI.Models.Student", "Student")
                        .WithMany("Payments")
                        .HasForeignKey("StudentId")
                        .IsRequired()
                        .HasConstraintName("FK_Payments_Student");

                    b.Navigation("Course");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("DeWaveFreeAPI.Models.RefreshToken", b =>
                {
                    b.HasOne("DeWaveFreeAPI.Models.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_RefreshTokens_Users");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DeWaveFreeAPI.Models.Student", b =>
                {
                    b.HasOne("DeWaveFreeAPI.Models.User", "User")
                        .WithOne("Student")
                        .HasForeignKey("DeWaveFreeAPI.Models.Student", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Students_Users");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DeWaveFreeAPI.Models.StudentCourse", b =>
                {
                    b.HasOne("DeWaveFreeAPI.Models.Course", "Course")
                        .WithMany("StudentCourses")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DeWaveFreeAPI.Models.Student", "Student")
                        .WithMany("StudentCourses")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("DeWaveFreeAPI.Models.StudentLessonProgress", b =>
                {
                    b.HasOne("DeWaveFreeAPI.Models.Lesson", "Lesson")
                        .WithMany("StudentLessonProgresses")
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DeWaveFreeAPI.Models.Student", "Student")
                        .WithMany("StudentLessonProgresses")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_slp_student");

                    b.Navigation("Lesson");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("DeWaveFreeAPI.Models.User", b =>
                {
                    b.HasOne("DeWaveFreeAPI.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .IsRequired()
                        .HasConstraintName("FK_Users_Roles");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("DeWaveFreeAPI.Models.BlockType", b =>
                {
                    b.Navigation("LessonBlocks");
                });

            modelBuilder.Entity("DeWaveFreeAPI.Models.Blog", b =>
                {
                    b.Navigation("BlogDetail");

                    b.Navigation("BlogTags");
                });

            modelBuilder.Entity("DeWaveFreeAPI.Models.Category", b =>
                {
                    b.Navigation("Courses");
                });

            modelBuilder.Entity("DeWaveFreeAPI.Models.Course", b =>
                {
                    b.Navigation("CourseDetails");

                    b.Navigation("CourseEventCourses");

                    b.Navigation("CourseFaqs");

                    b.Navigation("CourseInstructors");

                    b.Navigation("CourseLearningSections");

                    b.Navigation("CourseSections");

                    b.Navigation("Payments");

                    b.Navigation("StudentCourses");
                });

            modelBuilder.Entity("DeWaveFreeAPI.Models.CourseDetail", b =>
                {
                    b.Navigation("CourseImages");
                });

            modelBuilder.Entity("DeWaveFreeAPI.Models.CourseEvent", b =>
                {
                    b.Navigation("CourseEventCourses");

                    b.Navigation("EventAttendances");

                    b.Navigation("EventEnrollments");
                });

            modelBuilder.Entity("DeWaveFreeAPI.Models.CourseLearningSection", b =>
                {
                    b.Navigation("Lessons");
                });

            modelBuilder.Entity("DeWaveFreeAPI.Models.Instructor", b =>
                {
                    b.Navigation("CourseInstructors");
                });

            modelBuilder.Entity("DeWaveFreeAPI.Models.InstructorType", b =>
                {
                    b.Navigation("CourseInstructors");
                });

            modelBuilder.Entity("DeWaveFreeAPI.Models.Lesson", b =>
                {
                    b.Navigation("LessonBlocks");

                    b.Navigation("StudentLessonProgresses");
                });

            modelBuilder.Entity("DeWaveFreeAPI.Models.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("DeWaveFreeAPI.Models.Student", b =>
                {
                    b.Navigation("EventAttendances");

                    b.Navigation("EventEnrollments");

                    b.Navigation("Payments");

                    b.Navigation("StudentCourses");

                    b.Navigation("StudentLessonProgresses");
                });

            modelBuilder.Entity("DeWaveFreeAPI.Models.User", b =>
                {
                    b.Navigation("CourseEvents");

                    b.Navigation("Instructor");

                    b.Navigation("RefreshTokens");

                    b.Navigation("Student");
                });
#pragma warning restore 612, 618
        }
    }
}
